import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { canOpenRole, destinationForRole, parseDriverAuthorization, parseHandoverInput, parseVehicleInput, validOptionalEmail, validTripsFormUrl, validVehicleCode } from "../lib/operational/core.ts";

test("each identity role is redirected to its own operational page",()=>{assert.equal(destinationForRole("system_admin"),"/admin");assert.equal(destinationForRole("supervisor"),"/supervisor");assert.equal(destinationForRole("driver"),"/driver")});
test("role checks deny cross-role access",()=>{assert.equal(canOpenRole("driver",["system_admin"]),false);assert.equal(canOpenRole("supervisor",["system_admin"]),false);assert.equal(canOpenRole("system_admin",["system_admin"]),true)});
test("vehicle input is normalized and invalid data rejected",()=>{assert.equal(validVehicleCode("MX-001"),true);assert.deepEqual(parseVehicleInput({internalCode:" mx-001 ",plateNumber:" abc 123 ",make:"Ford",model:"Transit",modelYear:"2024",status:"active"}),{internalCode:"MX-001",plateNumber:"ABC 123",make:"Ford",model:"Transit",modelYear:2024,color:null,status:"active",notes:""});assert.throws(()=>parseVehicleInput({internalCode:"<script>",plateNumber:"x",make:"x",model:"x"}),/invalid_vehicle/)});
test("vehicle model year remains optional",()=>{assert.equal(parseVehicleInput({internalCode:"MX-002",plateNumber:"XYZ-2",make:"Ford",model:"Transit"}).modelYear,null)});
test("driver authorization validates shift, type and validity window",()=>{const result=parseDriverAuthorization({driverUserId:7,shiftType:"morning",assignmentType:"primary",validFrom:"2026-08-01T06:00:00Z",validTo:"2026-08-01T14:00:00Z"});assert.equal(result.driverUserId,7);assert.equal(result.shiftType,"morning");assert.throws(()=>parseDriverAuthorization({driverUserId:7,shiftType:"night"}),/invalid_assignment/);assert.throws(()=>parseDriverAuthorization({driverUserId:7,validFrom:"2026-08-02",validTo:"2026-08-01"}),/invalid_assignment/)});
test("handover input validates vehicle state readings and bounds notes",()=>{const result=parseHandoverInput({vehicleId:3,toDriverUserId:8,odometer:"1200.5",fuelLevel:"65",vehicleCondition:"good"});assert.equal(result.odometer,1200.5);assert.equal(result.fuelLevel,65);assert.throws(()=>parseHandoverInput({vehicleId:3,toDriverUserId:8,fuelLevel:101}),/invalid_handover/);assert.throws(()=>parseHandoverInput({vehicleId:3,toDriverUserId:8,vehicleCondition:"<script>"}),/invalid_handover/)});
test("optional email and trips links reject malformed or untrusted values",()=>{assert.equal(validOptionalEmail(""),true);assert.equal(validOptionalEmail("admin@example.invalid"),true);assert.equal(validOptionalEmail("bad@"),false);assert.equal(validTripsFormUrl("https://forms.gle/example"),true);assert.equal(validTripsFormUrl("https://docs.google.com/forms/d/e/example/viewform"),true);assert.equal(validTripsFormUrl("javascript:alert(1)"),false);assert.equal(validTripsFormUrl("https://docs.google.com.evil.example/forms/x"),false)});
test("required pages use server-side role guards and no operational dashboard contains mock metrics",async()=>{const pages=[["../app/admin/page.tsx","system_admin"],["../app/supervisor/page.tsx","supervisor"],["../app/driver/page.tsx","driver"]];for(const[path,role]of pages){const source=await readFile(new URL(path,import.meta.url),"utf8");assert.match(source,new RegExp(`requirePageRole\\(\\[\\\"${role}\\\"\\]\\)`));assert.doesNotMatch(source,/mock|demo|تجريبي/i)}const css=await readFile(new URL("../app/globals.css",import.meta.url),"utf8");assert.match(css,/@media\(max-width:420px\)/);});
