import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { canOpenRole, destinationForRole, parseDriverAuthorization, parseDriverInput, parseHandoverInput, parseVehicleInput, protectNationalId, validOptionalEmail, validTripsFormUrl, validVehicleCode } from "../lib/operational/core.ts";

test("each identity role is redirected to its own operational page",()=>{assert.equal(destinationForRole("system_admin"),"/admin");assert.equal(destinationForRole("supervisor"),"/supervisor");assert.equal(destinationForRole("driver"),"/driver")});
test("role checks deny cross-role access",()=>{assert.equal(canOpenRole("driver",["system_admin"]),false);assert.equal(canOpenRole("supervisor",["system_admin"]),false);assert.equal(canOpenRole("system_admin",["system_admin"]),true)});
test("vehicle input is normalized and invalid data rejected",()=>{assert.equal(validVehicleCode("MX-001"),true);assert.deepEqual(parseVehicleInput({internalCode:" mx-001 ",plateNumber:" abc 123 ",make:"Ford",model:"Transit",modelYear:"2024",status:"active"}),{internalCode:"MX-001",plateNumber:"ABC 123",make:"Ford",model:"Transit",modelYear:2024,color:null,vin:null,engineNumber:null,fuelType:null,currentOdometer:null,vehicleLicenseNumber:null,vehicleType:null,registrationExpiresAt:null,insuranceExpiresAt:null,insuranceCompany:null,location:null,status:"active",notes:""});assert.throws(()=>parseVehicleInput({internalCode:"<script>",plateNumber:"x",make:"x",model:"x"}),/invalid_vehicle/);assert.throws(()=>parseVehicleInput({internalCode:"MX-2",plateNumber:"x",make:"x",model:"x",vin:"BAD VIN"}),/invalid_vehicle/);assert.throws(()=>parseVehicleInput({internalCode:"MX-2",plateNumber:"x",make:"x",model:"x",currentOdometer:-1}),/invalid_vehicle/)});
test("vehicle model year remains optional",()=>{assert.equal(parseVehicleInput({internalCode:"MX-002",plateNumber:"XYZ-2",make:"Ford",model:"Transit"}).modelYear,null)});
test("driver authorization validates shift, type and validity window",()=>{const result=parseDriverAuthorization({driverUserId:7,shiftType:"night",assignmentType:"backup",validFrom:"2026-08-01T06:00:00Z",validTo:"2026-08-01T14:00:00Z"});assert.equal(result.driverUserId,7);assert.equal(result.shiftType,"night");assert.throws(()=>parseDriverAuthorization({driverUserId:7,shiftType:"alternate"}),/invalid_assignment/);assert.throws(()=>parseDriverAuthorization({driverUserId:7,assignmentType:"regular"}),/invalid_assignment/);assert.throws(()=>parseDriverAuthorization({driverUserId:7,validFrom:"2026-08-02",validTo:"2026-08-01"}),/invalid_assignment/)});
test("driver input requires operational fields and protects national id",async()=>{const driver=parseDriverInput({driverCode:"drv-001",fullName:"سائق اختبار",phone:"01000000001",nationalId:"12345678901234",primaryShift:"morning",employmentStatus:"active"});assert.equal(driver.driverCode,"DRV-001");const protectedId=await protectNationalId(driver.nationalId);assert.equal(protectedId.last4,"1234");assert.doesNotMatch(protectedId.hash,/12345678901234/);assert.throws(()=>parseDriverInput({driverCode:"D1",fullName:"x",phone:"1"}),/invalid_driver_profile/)});
test("handover input validates vehicle state readings and bounds notes",()=>{const result=parseHandoverInput({vehicleId:3,toDriverUserId:8,odometer:"1200.5",fuelLevel:"65",vehicleCondition:"good"});assert.equal(result.odometer,1200.5);assert.equal(result.fuelLevel,65);assert.throws(()=>parseHandoverInput({vehicleId:3,toDriverUserId:8,fuelLevel:101}),/invalid_handover/);assert.throws(()=>parseHandoverInput({vehicleId:3,toDriverUserId:8,vehicleCondition:"<script>"}),/invalid_handover/)});
test("optional email and trips links reject malformed or untrusted values",()=>{assert.equal(validOptionalEmail(""),true);assert.equal(validOptionalEmail("admin@example.invalid"),true);assert.equal(validOptionalEmail("bad@"),false);assert.equal(validTripsFormUrl("https://forms.gle/example"),true);assert.equal(validTripsFormUrl("https://docs.google.com/forms/d/e/example/viewform"),true);assert.equal(validTripsFormUrl("javascript:alert(1)"),false);assert.equal(validTripsFormUrl("https://docs.google.com.evil.example/forms/x"),false)});
test("required pages use server-side role guards and no operational dashboard contains mock metrics",async()=>{const pages=[["../app/admin/page.tsx","system_admin"],["../app/supervisor/page.tsx","supervisor"],["../app/driver/page.tsx","driver"]];for(const[path,role]of pages){const source=await readFile(new URL(path,import.meta.url),"utf8");assert.match(source,new RegExp(`requirePageRole\\(\\[\\\"${role}\\\"\\]\\)`));assert.doesNotMatch(source,/mock|demo|تجريبي/i)}const css=await readFile(new URL("../app/globals.css",import.meta.url),"utf8");assert.match(css,/@media\(max-width:420px\)/);});
test("operational code has no Sheets import or synchronization path",async()=>{const files=["../db/operational-store.ts","../app/api/operational/drivers/route.ts","../app/api/operational/vehicles/route.ts","../components/operational-managers.tsx","../components/vehicle-manager.tsx"];for(const file of files){const source=await readFile(new URL(file,import.meta.url),"utf8");assert.doesNotMatch(source,/sheets\.google|google sheets|spreadsheet|syncFrom|importDrivers/i)}const store=await readFile(new URL("../db/operational-store.ts",import.meta.url),"utf8");assert.match(store,/manual_admin/);});
test("admin UI exposes complete manual driver and vehicle creation fields",async()=>{const drivers=await readFile(new URL("../components/operational-managers.tsx",import.meta.url),"utf8");for(const label of ["كود السائق","الاسم الكامل","الهاتف","رقم الرخصة","نوع الرخصة","تاريخ التعيين","الوردية الأساسية","هاتف الطوارئ"]){assert.match(drivers,new RegExp(label))}const vehicles=await readFile(new URL("../components/vehicle-manager.tsx",import.meta.url),"utf8");for(const label of ["الكود الداخلي","رقم اللوحة","رقم الهيكل VIN","رقم المحرك","نوع الوقود","العداد الحالي","رقم رخصة السيارة","شركة التأمين","تصفية بالموقع"]){assert.match(vehicles,new RegExp(label))}assert.doesNotMatch(await readFile(new URL("../components/account-manager.tsx",import.meta.url),"utf8"),/option value=\"driver\"/);});
