"use client";

import { useCallback, useEffect, useState } from "react";
import { DriverProfileFields, driverApi, emptyDriverProfile, type DriverProfileForm } from "./driver-profile-manager";

type DocumentRow={id:number;document_type:string;original_filename:string;mime_type:string;file_size:number;issue_date:string|null;expiry_date:string|null;verification_status:string;rejection_reason:string|null;archived_at:string|null};
type Detail={profile:Record<string,unknown>;documents:DocumentRow[];relations:{assignments:Record<string,unknown>[];handovers:Record<string,unknown>[];audit:Record<string,unknown>[]}};
const tabs=["البيانات الأساسية","العمل والوردية","رخصة القيادة","المستندات","السيارة والتصاريح","سجل الاستلام والتسليم","سجل العمليات"];
const documentTypes:Record<string,string>={profile_photo:"الصورة الشخصية",national_id_front:"وجه البطاقة",national_id_back:"ظهر البطاقة",driving_license_front:"وجه الرخصة",driving_license_back:"ظهر الرخصة",criminal_record:"صحيفة الحالة الجنائية",drug_test:"تحليل المخدرات",employment_document:"مستند التوظيف",other:"أخرى"};

function profileToForm(profile:Record<string,unknown>):DriverProfileForm{return {...emptyDriverProfile,driverCode:String(profile.driver_code??""),fullName:String(profile.full_name??""),phone:String(profile.phone??""),secondaryPhone:String(profile.secondary_phone??""),email:String(profile.email??""),dateOfBirth:String(profile.date_of_birth??""),address:String(profile.address??""),branchOrLocation:String(profile.branch_or_location??""),hireDate:String(profile.hire_date??""),primaryShift:String(profile.primary_shift??"flexible"),employmentStatus:String(profile.employment_status??"active"),emergencyContactName:String(profile.emergency_contact_name??""),emergencyContactPhone:String(profile.emergency_contact_phone??""),notes:String(profile.notes??""),nationalId:"",drivingLicenseNumber:String(profile.driving_license_number??""),drivingLicenseType:String(profile.driving_license_type??""),drivingLicenseIssueDate:String(profile.driving_license_issue_date??""),drivingLicenseExpiry:String(profile.driving_license_expiry??""),drivingLicenseStatus:String(profile.driving_license_status??"expired"),drivingLicenseNotes:String(profile.driving_license_notes??""),criminalRecordStatus:String(profile.criminal_record_status??"not_provided"),criminalRecordIssueDate:String(profile.criminal_record_issue_date??""),criminalRecordExpiry:String(profile.criminal_record_expiry??""),criminalRecordReference:String(profile.criminal_record_reference??""),criminalRecordNotes:String(profile.criminal_record_notes??""),drugTestStatus:String(profile.drug_test_status??"not_provided"),drugTestDate:String(profile.drug_test_date??""),drugTestExpiry:String(profile.drug_test_expiry??""),drugTestLab:String(profile.drug_test_lab??""),drugTestReference:String(profile.drug_test_reference??""),drugTestNotes:String(profile.drug_test_notes??"")}}

function AlertStrip({profile,documents,today,soon}:{profile:Record<string,unknown>;documents:DocumentRow[];today:string;soon:string}){const alerts:string[]=[];const expiry=String(profile.driving_license_expiry??"");if(!documents.some(document=>!document.archived_at&&['national_id_front','national_id_back'].includes(document.document_type)))alerts.push("البطاقة غير موجودة");if(profile.driving_license_status==='expired'||(expiry&&expiry<today))alerts.push("رخصة القيادة منتهية");else if(expiry&&expiry<=soon)alerts.push("رخصة القيادة ستنتهي قريبًا");if(profile.criminal_record_status==='expired')alerts.push("صحيفة الحالة الجنائية منتهية");if(['expired','not_provided'].includes(String(profile.drug_test_status)))alerts.push("تحليل المخدرات مطلوب أو منتهي");if(profile.account_status!=='active')alerts.push("الحساب معطل");return alerts.length?<div className="driver-alert-strip" role="alert">{alerts.map(alert=><span key={alert}>{alert}</span>)}</div>:<div className="driver-alert-strip ok">لا توجد تنبيهات حرجة في الملف.</div>}

export function DriverProfileDetails({driverId,today,soon}:{driverId:number;today:string;soon:string}){const[data,setData]=useState<Detail|null>(null),[form,setForm]=useState<DriverProfileForm>(emptyDriverProfile),[tab,setTab]=useState(0),[editing,setEditing]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[revealed,setRevealed]=useState<string|null>(null),[storageConfigured,setStorageConfigured]=useState(false),[file,setFile]=useState<File|null>(null),[documentType,setDocumentType]=useState("profile_photo"),[issueDate,setIssueDate]=useState(""),[expiryDate,setExpiryDate]=useState("");
  const load=useCallback(async()=>{const detail=await driverApi<Detail>(`/api/operational/drivers/${driverId}`);setData(detail);setForm(profileToForm(detail.profile));const docs=await driverApi<{storageConfigured:boolean}>(`/api/operational/drivers/${driverId}/documents`);setStorageConfigured(docs.storageConfigured)},[driverId]);
  useEffect(()=>{let active=true;void Promise.all([driverApi<Detail>(`/api/operational/drivers/${driverId}`),driverApi<{storageConfigured:boolean}>(`/api/operational/drivers/${driverId}/documents`)]).then(([detail,docs])=>{if(active){setData(detail);setForm(profileToForm(detail.profile));setStorageConfigured(docs.storageConfigured)}},error=>{if(active)setMessage(error instanceof Error?error.message:"تعذر تحميل الملف")});return()=>{active=false}},[driverId]);
  async function save(){setBusy(true);setMessage("");try{await driverApi(`/api/operational/drivers/${driverId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setEditing(false);setMessage("تم تحديث ملف الكابتن.");await load()}catch(error){setMessage(error instanceof Error?error.message:"تعذر الحفظ")}finally{setBusy(false)}}
  async function reveal(){setBusy(true);try{const output=await driverApi<{nationalId:string|null}>(`/api/operational/drivers/${driverId}/national-id`,{method:"POST"});setRevealed(output.nationalId);setMessage("تم تسجيل عملية إظهار الرقم القومي في سجل العمليات.")}catch(error){setMessage(error instanceof Error?error.message:"تعذر الإظهار")}finally{setBusy(false)}}
  async function upload(){if(!file)return;setBusy(true);try{const body=new FormData();body.set("file",file);body.set("documentType",documentType);body.set("issueDate",issueDate);body.set("expiryDate",expiryDate);await driverApi(`/api/operational/drivers/${driverId}/documents`,{method:"POST",body});setFile(null);setMessage("تم رفع المستند إلى مساحة Google Drive الخاصة وتسجيل بياناته.");await load()}catch(error){setMessage(error instanceof Error?error.message:"تعذر الرفع")}finally{setBusy(false)}}
  async function archive(id:number){setBusy(true);try{await driverApi(`/api/operational/driver-documents/${id}`,{method:"DELETE"});setMessage("تمت أرشفة المستند منطقيًا دون حذف سجل التدقيق.");await load()}catch(error){setMessage(error instanceof Error?error.message:"تعذر الأرشفة")}finally{setBusy(false)}}
  async function review(id:number,status:'verified'|'rejected'){const rejectionReason=status==='rejected'?window.prompt("سبب الرفض")?.trim():"";if(status==='rejected'&&!rejectionReason)return;setBusy(true);try{await driverApi(`/api/operational/driver-documents/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,rejectionReason})});setMessage(status==='verified'?"تم اعتماد المستند.":"تم رفض المستند مع تسجيل السبب.");await load()}catch(error){setMessage(error instanceof Error?error.message:"تعذر مراجعة المستند")}finally{setBusy(false)}}
  if(!data)return <section className="op-panel"><p>{message||"جارٍ تحميل ملف الكابتن…"}</p></section>;const p=data.profile;
  return <div className="op-manager"><AlertStrip profile={p} documents={data.documents} today={today} soon={soon}/><section className="op-panel driver-profile-header"><div><p className="op-kicker">{String(p.driver_code)}</p><h2>{String(p.full_name)}</h2><p>{String(p.phone)} — {String(p.branch_or_location??"لا يوجد فرع")}</p></div><button className="op-primary" onClick={()=>setEditing(value=>!value)}>{editing?"إلغاء التعديل":"تعديل البيانات"}</button></section><nav className="driver-tabs" aria-label="أقسام ملف الكابتن">{tabs.map((label,index)=><button key={label} className={tab===index?"active":""} onClick={()=>setTab(index)}>{label}</button>)}</nav>{message&&<p className="op-message" role="status">{message}</p>}
    {editing?<section className="op-panel"><DriverProfileFields form={form} setForm={setForm} editing/><button className="op-primary" disabled={busy} onClick={()=>void save()}>حفظ التعديلات</button></section>:<>
      {tab===0&&<section className="op-panel detail-grid"><Info label="الاسم" value={p.full_name}/><Info label="كود الكابتن" value={p.driver_code}/><Info label="الهاتف" value={p.phone}/><Info label="هاتف ثانوي" value={p.secondary_phone}/><Info label="البريد" value={p.email}/><Info label="تاريخ الميلاد" value={p.date_of_birth}/><Info label="العنوان" value={p.address}/><Info label="الرقم القومي" value={revealed??p.national_id_masked}/><button className="op-secondary" disabled={busy||!p.national_id_masked} onClick={()=>void reveal()}>إظهار الرقم كاملًا</button></section>}
      {tab===1&&<section className="op-panel detail-grid"><Info label="الفرع أو الموقع" value={p.branch_or_location}/><Info label="تاريخ التعيين" value={p.hire_date}/><Info label="الوردية الأساسية" value={p.primary_shift}/><Info label="الحالة الوظيفية" value={p.employment_status}/><Info label="اسم جهة اتصال الطوارئ" value={p.emergency_contact_name}/><Info label="هاتف الطوارئ" value={p.emergency_contact_phone}/><Info label="ملاحظات" value={p.notes}/></section>}
      {tab===2&&<section className="op-panel"><div className="detail-grid"><Info label="رقم الرخصة" value={p.driving_license_number}/><Info label="النوع" value={p.driving_license_type}/><Info label="تاريخ الإصدار" value={p.driving_license_issue_date}/><Info label="تاريخ الانتهاء" value={p.driving_license_expiry}/><Info label="الحالة" value={p.driving_license_status}/><Info label="الملاحظات" value={p.driving_license_notes}/></div><hr/><h3>صحيفة الحالة الجنائية</h3><div className="detail-grid"><Info label="الحالة" value={p.criminal_record_status}/><Info label="الإصدار" value={p.criminal_record_issue_date}/><Info label="الانتهاء" value={p.criminal_record_expiry}/><Info label="المرجع" value={p.criminal_record_reference}/></div><h3>تحليل المخدرات</h3><div className="detail-grid"><Info label="النتيجة والحالة" value={p.drug_test_status}/><Info label="التاريخ" value={p.drug_test_date}/><Info label="الاختبار التالي" value={p.drug_test_expiry}/><Info label="المعمل" value={p.drug_test_lab}/></div></section>}
      {tab===3&&<section className="op-panel"><h2>المستندات والصور</h2>{storageConfigured?<div className="document-upload"><label>نوع المستند<select value={documentType} onChange={e=>setDocumentType(e.target.value)}>{Object.entries(documentTypes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>تاريخ الإصدار<input type="date" value={issueDate} onChange={e=>setIssueDate(e.target.value)}/></label><label>تاريخ الانتهاء<input type="date" value={expiryDate} onChange={e=>setExpiryDate(e.target.value)}/></label><label>ملف JPG أو PNG أو WEBP أو PDF<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button className="op-primary" disabled={busy||!file} onClick={()=>void upload()}>رفع المستند الخاص</button></div>:<div className="storage-blocker" role="status"><strong>رفع المستندات غير مفعّل على هذه البيئة</strong><p>يلزم إعداد Service Account ومجلد Google Drive خاص في Cloudflare Secrets. لا يوجد زر رفع وهمي، ولا تُستخدم روابط عامة.</p></div>}<div className="op-table-wrap"><table><thead><tr><th>النوع</th><th>الملف</th><th>الحجم</th><th>الانتهاء</th><th>التحقق</th><th>إجراءات</th></tr></thead><tbody>{data.documents.filter(d=>!d.archived_at).map(document=><tr key={document.id}><td>{documentTypes[document.document_type]??document.document_type}</td><td>{document.original_filename}</td><td>{Math.ceil(document.file_size/1024)} KB</td><td>{document.expiry_date??"—"}</td><td>{document.verification_status}</td><td><a href={`/api/operational/driver-documents/${document.id}`} target="_blank" rel="noreferrer">عرض/تنزيل آمن</a> <button disabled={busy} onClick={()=>void review(document.id,'verified')}>اعتماد</button> <button disabled={busy} onClick={()=>void review(document.id,'rejected')}>رفض</button> <button disabled={busy} onClick={()=>void archive(document.id)}>أرشفة</button></td></tr>)}</tbody></table></div></section>}
      {tab===4&&<RelationTable title="السيارة والتصاريح" rows={data.relations.assignments} columns={["internal_code","plate_number","shift_type","assignment_type","status","has_custody"]}/>} {tab===5&&<RelationTable title="سجل الاستلام والتسليم" rows={data.relations.handovers} columns={["internal_code","from_driver_name","to_driver_name","handed_over_at","vehicle_condition"]}/>} {tab===6&&<RelationTable title="سجل العمليات" rows={data.relations.audit} columns={["action","result","created_at"]}/>}</>}
  </div>}

function Info({label,value}:{label:string;value:unknown}){return <div className="detail-item"><small>{label}</small><strong>{value===null||value===undefined||value===""?"—":String(value)}</strong></div>}
function RelationTable({title,rows,columns}:{title:string;rows:Record<string,unknown>[];columns:string[]}){return <section className="op-panel"><h2>{title}</h2>{rows.length?<div className="op-table-wrap"><table><thead><tr>{columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row.id??index)}>{columns.map(column=><td key={column}>{String(row[column]??"—")}</td>)}</tr>)}</tbody></table></div>:<p>لا توجد سجلات.</p>}</section>}
