"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

export type DriverProfileForm = typeof emptyDriverProfile;
export const emptyDriverProfile={driverCode:"",fullName:"",phone:"",secondaryPhone:"",email:"",dateOfBirth:"",gender:"",nationality:"",maritalStatus:"",religion:"",occupation:"",address:"",branchOrLocation:"",hireDate:"",primaryShift:"flexible",employmentStatus:"active",emergencyContactName:"",emergencyContactPhone:"",notes:"",nationalId:"",nationalIdExpiry:"",nationalIdCardSerial:"",drivingLicenseNumber:"",drivingLicenseType:"",drivingLicenseTrafficDepartment:"",drivingLicenseTrafficUnit:"",drivingLicenseCategory:"",drivingLicenseIssueDate:"",drivingLicenseExpiry:"",drivingLicenseStatus:"expired",drivingLicenseNotes:"",criminalRecordStatus:"not_provided",criminalRecordIssueDate:"",criminalRecordExpiry:"",criminalRecordReference:"",criminalRecordNotes:"",drugTestStatus:"not_provided",drugTestDate:"",drugTestExpiry:"",drugTestLab:"",drugTestReference:"",drugTestNotes:""};

export async function driverApi<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,init);const data=await response.json() as T&{error?:string};if(!response.ok)throw new Error(data.error??"تعذر إتمام العملية");return data}

const employment:Record<string,string>={active:"نشط",vacation:"إجازة",suspended:"موقوف",resigned:"مستقيل",terminated:"منتهي الخدمة"};
const shifts:Record<string,string>={morning:"صباحية",evening:"مسائية",night:"ليلية",flexible:"مرنة"};
const licenceStatuses:Record<string,string>={valid:"سارية",expiring:"قاربت الانتهاء",expired:"منتهية",suspended:"موقوفة"};

function TextField({form,setForm,name,label,type="text",required=false}:{form:DriverProfileForm;setForm:(value:DriverProfileForm)=>void;name:keyof DriverProfileForm;label:string;type?:string;required?:boolean}){return <label>{label}<input required={required} type={type} value={form[name]} onChange={event=>setForm({...form,[name]:event.target.value})}/></label>}

export function DriverProfileFields({form,setForm,editing=false}:{form:DriverProfileForm;setForm:(value:DriverProfileForm)=>void;editing?:boolean}){
  return <div className="driver-profile-sections">
    <fieldset><legend>البيانات الأساسية</legend><div className="op-form-grid"><TextField form={form} setForm={setForm} name="driverCode" label="كود الكابتن" required/><TextField form={form} setForm={setForm} name="fullName" label="الاسم الكامل" required/><TextField form={form} setForm={setForm} name="phone" label="الهاتف" required/><TextField form={form} setForm={setForm} name="secondaryPhone" label="هاتف ثانوي"/><TextField form={form} setForm={setForm} name="email" label="البريد الإلكتروني" type="email"/><TextField form={form} setForm={setForm} name="dateOfBirth" label="تاريخ الميلاد" type="date"/><label>الجنس<select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option value="">غير محدد</option><option value="male">ذكر</option><option value="female">أنثى</option></select></label><TextField form={form} setForm={setForm} name="nationality" label="الجنسية"/><label>الحالة الاجتماعية<select value={form.maritalStatus} onChange={e=>setForm({...form,maritalStatus:e.target.value})}><option value="">غير محددة</option><option value="single">أعزب</option><option value="married">متزوج</option><option value="divorced">مطلق</option><option value="widowed">أرمل</option></select></label><TextField form={form} setForm={setForm} name="religion" label="الديانة (اختياري)"/><TextField form={form} setForm={setForm} name="occupation" label="المهنة"/><TextField form={form} setForm={setForm} name="address" label="العنوان"/><TextField form={form} setForm={setForm} name="branchOrLocation" label="الفرع أو الموقع"/><TextField form={form} setForm={setForm} name="hireDate" label="تاريخ التعيين" type="date"/><label>الوردية الأساسية<select value={form.primaryShift} onChange={e=>setForm({...form,primaryShift:e.target.value})}>{Object.entries(shifts).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>الحالة الوظيفية<select value={form.employmentStatus} onChange={e=>setForm({...form,employmentStatus:e.target.value})}>{Object.entries(employment).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><TextField form={form} setForm={setForm} name="emergencyContactName" label="اسم جهة اتصال الطوارئ"/><TextField form={form} setForm={setForm} name="emergencyContactPhone" label="هاتف الطوارئ"/><TextField form={form} setForm={setForm} name="notes" label="ملاحظات"/></div></fieldset>
    <fieldset><legend>الرقم القومي</legend><p className="op-muted">يُشفّر داخل D1 وتُستخدم بصمة مستقلة لمنع التكرار. لا يظهر كاملًا إلا بإجراء صريح لمدير النظام.</p><div className="op-form-grid"><TextField form={form} setForm={setForm} name="nationalId" label={editing?"رقم قومي جديد — اتركه فارغًا للاحتفاظ بالحالي":"الرقم القومي"}/><TextField form={form} setForm={setForm} name="nationalIdExpiry" label="انتهاء بطاقة الرقم القومي" type="date"/><TextField form={form} setForm={setForm} name="nationalIdCardSerial" label="الرقم المسلسل للبطاقة"/></div></fieldset>
    <fieldset><legend>رخصة القيادة</legend><div className="op-form-grid"><TextField form={form} setForm={setForm} name="drivingLicenseNumber" label="رقم رخصة القيادة"/><TextField form={form} setForm={setForm} name="drivingLicenseType" label="نوع الرخصة"/><TextField form={form} setForm={setForm} name="drivingLicenseTrafficDepartment" label="إدارة مرور الرخصة"/><TextField form={form} setForm={setForm} name="drivingLicenseTrafficUnit" label="وحدة مرور الرخصة"/><TextField form={form} setForm={setForm} name="drivingLicenseCategory" label="فئة الرخصة"/><TextField form={form} setForm={setForm} name="drivingLicenseIssueDate" label="تاريخ الإصدار" type="date"/><TextField form={form} setForm={setForm} name="drivingLicenseExpiry" label="تاريخ الانتهاء" type="date"/><label>حالة الرخصة<select value={form.drivingLicenseStatus} onChange={e=>setForm({...form,drivingLicenseStatus:e.target.value})}><option value="valid">سارية</option><option value="expiring">قاربت الانتهاء</option><option value="expired">منتهية</option><option value="suspended">موقوفة</option></select></label><TextField form={form} setForm={setForm} name="drivingLicenseNotes" label="ملاحظات الرخصة"/></div></fieldset>
    <fieldset><legend>صحيفة الحالة الجنائية</legend><div className="op-form-grid"><label>الحالة<select value={form.criminalRecordStatus} onChange={e=>setForm({...form,criminalRecordStatus:e.target.value})}><option value="not_provided">غير مقدمة</option><option value="pending">قيد المراجعة</option><option value="valid">سارية</option><option value="expired">منتهية</option><option value="rejected">مرفوضة</option></select></label><TextField form={form} setForm={setForm} name="criminalRecordIssueDate" label="تاريخ الإصدار" type="date"/><TextField form={form} setForm={setForm} name="criminalRecordExpiry" label="تاريخ الانتهاء" type="date"/><TextField form={form} setForm={setForm} name="criminalRecordReference" label="المرجع"/><TextField form={form} setForm={setForm} name="criminalRecordNotes" label="ملاحظات الصحيفة"/></div></fieldset>
    <fieldset><legend>تحليل المخدرات</legend><div className="op-form-grid"><label>النتيجة والحالة<select value={form.drugTestStatus} onChange={e=>setForm({...form,drugTestStatus:e.target.value})}><option value="not_provided">غير مقدم</option><option value="pending">قيد الانتظار</option><option value="negative">سلبي</option><option value="positive">إيجابي</option><option value="expired">منتهي</option></select></label><TextField form={form} setForm={setForm} name="drugTestDate" label="تاريخ التحليل" type="date"/><TextField form={form} setForm={setForm} name="drugTestExpiry" label="الاختبار التالي/الانتهاء" type="date"/><TextField form={form} setForm={setForm} name="drugTestLab" label="المعمل"/><TextField form={form} setForm={setForm} name="drugTestReference" label="المرجع"/><TextField form={form} setForm={setForm} name="drugTestNotes" label="ملاحظات التحليل"/></div></fieldset>
  </div>
}

type Driver={id:number;driver_code:string;full_name:string;phone:string;primary_shift:string;branch_or_location:string|null;employment_status:string;driving_license_status:string;driving_license_expiry:string|null;document_count:number;document_alert_count:number};

export function DriverProfilesManager(){const[drivers,setDrivers]=useState<Driver[]>([]),[form,setForm]=useState(emptyDriverProfile),[adding,setAdding]=useState(false),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[shift,setShift]=useState(""),[branch,setBranch]=useState(""),[message,setMessage]=useState(""),[secret,setSecret]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const p=new URLSearchParams({q:query,status,shift,branch});setDrivers((await driverApi<{drivers:Driver[]}>(`/api/operational/drivers?${p}`)).drivers)},[query,status,shift,branch]);
  useEffect(()=>{let active=true;const p=new URLSearchParams({q:query,status,shift,branch});void driverApi<{drivers:Driver[]}>(`/api/operational/drivers?${p}`).then(output=>{if(active)setDrivers(output.drivers)},error=>{if(active)setMessage(error instanceof Error?error.message:"تعذر التحميل")});return()=>{active=false}},[query,status,shift,branch]);
  async function create(){setBusy(true);setMessage("");setSecret("");try{const output=await driverApi<{id:number;temporaryPassword:string}>("/api/operational/drivers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setSecret(output.temporaryPassword);setForm(emptyDriverProfile);setAdding(false);setMessage("تم إنشاء حساب الكابتن وملفه معًا. كلمة المرور المؤقتة تظهر مرة واحدة فقط.");await load()}catch(error){setMessage(error instanceof Error?error.message:"تعذر إنشاء الكابتن")}finally{setBusy(false)}}
  async function reset(id:number){setBusy(true);setSecret("");try{const output=await driverApi<{temporaryPassword:string}>(`/api/operational/users/${id}/reset-password`,{method:"POST"});setSecret(output.temporaryPassword);setMessage("تم إلغاء الجلسات وإصدار كلمة مرور مؤقتة جديدة.")}catch(error){setMessage(error instanceof Error?error.message:"تعذر إعادة التعيين")}finally{setBusy(false)}}
  async function toggle(driver:Driver){setBusy(true);try{const next=driver.employment_status==='active'?'suspended':'active';await driverApi(`/api/operational/drivers/${driver.id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:next})});setMessage(next==='active'?"تمت إعادة تفعيل الكابتن.":"تم تعطيل الحساب وإنهاء جلساته وتصاريحه المفتوحة.");await load()}catch(error){setMessage(error instanceof Error?error.message:"تعذر تحديث الحالة")}finally{setBusy(false)}}
  return <div className="op-manager"><section className="op-panel driver-list-head"><div><h2>ملفات الكباتن</h2><p>ملفات شخصية ووظيفية وتشغيلية مستقلة عن حسابات الدخول.</p></div><button className="op-primary" onClick={()=>setAdding(value=>!value)}>{adding?"إغلاق النموذج":"إضافة كابتن"}</button></section>{adding&&<section className="op-panel"><h2>إضافة كابتن</h2><DriverProfileFields form={form} setForm={setForm}/><button className="op-primary" disabled={busy} onClick={()=>void create()}>{busy?"جارٍ الإنشاء…":"إنشاء الحساب والملف"}</button></section>}{secret&&<section className="op-secret" role="status"><strong>كلمة المرور المؤقتة — تظهر الآن فقط</strong><code>{secret}</code></section>}{message&&<p className="op-message" role="status">{message}</p>}<section className="op-panel"><div className="op-toolbar"><input aria-label="بحث الكباتن" placeholder="بحث بالاسم أو الكود أو الهاتف أو الرقم القومي" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="تصفية الحالة" value={status} onChange={e=>setStatus(e.target.value)}><option value="">كل الحالات</option>{Object.entries(employment).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="تصفية الوردية" value={shift} onChange={e=>setShift(e.target.value)}><option value="">كل الورديات</option>{Object.entries(shifts).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input aria-label="تصفية الفرع" placeholder="الفرع أو الموقع" value={branch} onChange={e=>setBranch(e.target.value)}/></div><div className="op-table-wrap"><table><thead><tr><th>الكابتن</th><th>الهاتف</th><th>الوردية</th><th>الفرع</th><th>الرخصة</th><th>المستندات</th><th>الحالة</th><th>إجراءات</th></tr></thead><tbody>{drivers.map(driver=><tr key={driver.id}><td><strong>{driver.full_name}</strong><br/><small>{driver.driver_code}</small></td><td>{driver.phone}</td><td>{shifts[driver.primary_shift]??driver.primary_shift}</td><td>{driver.branch_or_location??"—"}</td><td>{licenceStatuses[driver.driving_license_status]??driver.driving_license_status}{driver.driving_license_expiry?` — ${driver.driving_license_expiry}`:""}</td><td>{Number(driver.document_count)||0}{Number(driver.document_alert_count)>0&&<span className="op-badge danger"> {driver.document_alert_count} تنبيه</span>}</td><td>{employment[driver.employment_status]??driver.employment_status}</td><td><Link href={`/admin/settings/drivers/${driver.id}`}>فتح الملف</Link> <button disabled={busy} onClick={()=>void reset(driver.id)}>إعادة كلمة المرور</button> <button disabled={busy} onClick={()=>void toggle(driver)}>{driver.employment_status==='active'?"تعطيل":"إعادة تفعيل"}</button></td></tr>)}</tbody></table></div></section></div>}
