"use client";
import { useEffect, useState } from "react";
import { destinationForRole } from "@/lib/operational/core";
import type { PublicIdentityUser } from "@/lib/identity/core";

export function LoginForm(){const[code,setCode]=useState("");const[password,setPassword]=useState("");const[user,setUser]=useState<PublicIdentityUser|null>(null);const[nextPassword,setNextPassword]=useState("");const[confirmation,setConfirmation]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
useEffect(()=>{void fetch('/api/auth/me',{cache:'no-store'}).then(async r=>{if(!r.ok)return;const d=await r.json() as {user:PublicIdentityUser};if(d.user.mustChangePassword)setUser(d.user);else window.location.replace(destinationForRole(d.user.role));}).catch(()=>undefined)},[]);
async function login(){setBusy(true);setError("");try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({loginCode:code,password})});const d=await r.json() as {user?:PublicIdentityUser;error?:string};if(!r.ok||!d.user)throw new Error(d.error??'تعذر تسجيل الدخول');if(d.user.mustChangePassword)setUser(d.user);else window.location.replace(destinationForRole(d.user.role));}catch(e){setError(e instanceof Error?e.message:'تعذر تسجيل الدخول')}finally{setBusy(false)}}
async function change(){setBusy(true);setError("");try{const r=await fetch('/api/auth/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:nextPassword,confirmation})});const d=await r.json() as {user?:PublicIdentityUser;error?:string};if(!r.ok||!d.user)throw new Error(d.error??'تعذر تغيير كلمة المرور');window.location.replace(destinationForRole(d.user.role));}catch(e){setError(e instanceof Error?e.message:'تعذر تغيير كلمة المرور')}finally{setBusy(false)}}
return <main className="op-login"><section className="op-login-card"><div className="op-logo"><span>MOVE</span><b>X</b></div>{user?<><p className="op-kicker">أول دخول</p><h1>غيّر كلمة المرور المؤقتة</h1><p>لن تتمكن من فتح النظام قبل إنشاء كلمة مرور خاصة بك.</p><form onSubmit={e=>{e.preventDefault();void change()}}><label>كلمة المرور الجديدة<input type="password" autoComplete="new-password" value={nextPassword} onChange={e=>setNextPassword(e.target.value)}/></label><label>التأكيد<input type="password" autoComplete="new-password" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label>{error&&<p className="op-error">{error}</p>}<button disabled={busy||nextPassword.length<8}>{busy?'جارٍ الحفظ…':'حفظ ومتابعة'}</button></form></>:<><p className="op-kicker">بوابة التشغيل</p><h1>تسجيل الدخول إلى <bdi dir="ltr">Move X</bdi></h1><p>استخدم كود الحساب وكلمة المرور المخصصة لك.</p><form onSubmit={e=>{e.preventDefault();void login()}}><label>كود الدخول<input autoComplete="username" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/\s/g,'').slice(0,24))}/></label><label>كلمة المرور<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="op-error">{error}</p>}<button disabled={busy||!code||!password}>{busy?'جارٍ التحقق…':'دخول'}</button></form></>}</section></main>}
