"use client";

import { useCallback, useEffect, useState } from "react";

async function api<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } });
  const data = await response.json() as T & { error?: string };
  if (!response.ok) throw new Error(data.error ?? "تعذر إتمام العملية");
  return data;
}

type User = {id:number;loginCode:string;displayName:string;email:string|null;phone:string|null;role:string;status:string;mustChangePassword:boolean};
const emptyUser = { loginCode:"", displayName:"", email:"", phone:"", role:"driver", status:"active" };
export function UserManager({initialRole=""}:{initialRole?:string}) {
  const [users,setUsers]=useState<User[]>([]), [form,setForm]=useState(emptyUser), [editing,setEditing]=useState<number|null>(null);
  const [query,setQuery]=useState(""), [role,setRole]=useState(initialRole), [status,setStatus]=useState(""), [message,setMessage]=useState(""), [secret,setSecret]=useState("");
  const load=useCallback(async()=>{const p=new URLSearchParams({q:query,role,status});setUsers((await api<{users:User[]}>(`/api/operational/users?${p}`)).users)},[query,role,status]);
  useEffect(()=>{let active=true;const p=new URLSearchParams({q:query,role,status});void api<{users:User[]}>(`/api/operational/users?${p}`).then(x=>{if(active)setUsers(x.users)},e=>{if(active)setMessage(e.message)});return()=>{active=false}},[query,role,status]);
  async function save(){setMessage("");setSecret("");try{if(editing){await api(`/api/operational/users/${editing}`,{method:"PATCH",body:JSON.stringify(form)});}else{const out=await api<{temporaryPassword:string}>("/api/operational/users",{method:"POST",body:JSON.stringify(form)});setSecret(out.temporaryPassword);}setForm(emptyUser);setEditing(null);await load();setMessage("تم حفظ المستخدم.");}catch(e){setMessage(e instanceof Error?e.message:"تعذر الحفظ")}}
  async function reset(id:number){try{const out=await api<{temporaryPassword:string}>(`/api/operational/users/${id}/reset-password`,{method:"POST"});setSecret(out.temporaryPassword);setMessage("تم إلغاء الجلسات وإصدار كلمة مؤقتة جديدة.");await load();}catch(e){setMessage(e instanceof Error?e.message:"تعذر إعادة التعيين")}}
  return <div className="op-manager"><section className="op-panel"><h2>{editing?"تعديل المستخدم":"إضافة مستخدم"}</h2><div className="op-form-grid"><label>كود الدخول<input value={form.loginCode} onChange={e=>setForm({...form,loginCode:e.target.value.toUpperCase()})}/></label><label>الاسم<input value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label>البريد<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>الهاتف<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>الدور<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="driver">سائق</option><option value="supervisor">مشرف</option><option value="system_admin">مدير نظام</option></select></label><label>الحالة<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">نشط</option><option value="inactive">غير نشط</option></select></label></div><button className="op-primary" onClick={()=>void save()}>حفظ</button>{editing&&<button className="op-secondary" onClick={()=>{setEditing(null);setForm(emptyUser)}}>إلغاء</button>}{secret&&<div className="op-secret" role="status"><strong>كلمة المرور المؤقتة — تظهر الآن فقط</strong><code>{secret}</code></div>}{message&&<p className="op-message">{message}</p>}</section><section className="op-panel"><div className="op-toolbar"><input placeholder="بحث بالاسم أو الكود" value={query} onChange={e=>setQuery(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)}><option value="">كل الأدوار</option><option value="driver">السائقون</option><option value="supervisor">المشرفون</option><option value="system_admin">مديرو النظام</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">كل الحالات</option><option value="active">نشط</option><option value="inactive">غير نشط</option></select></div><div className="op-table-wrap"><table><thead><tr><th>الاسم</th><th>الكود</th><th>الدور</th><th>الحالة</th><th>إجراءات</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.displayName}</td><td>{u.loginCode}</td><td>{u.role}</td><td>{u.status==='active'?'نشط':'غير نشط'}</td><td><button onClick={()=>{setEditing(u.id);setForm({loginCode:u.loginCode,displayName:u.displayName,email:u.email??"",phone:u.phone??"",role:u.role,status:u.status})}}>تعديل</button> <button onClick={()=>void reset(u.id)}>إعادة كلمة المرور</button></td></tr>)}</tbody></table></div></section></div>
}

type Vehicle={id:number;internal_code:string;plate_number:string;make:string;model:string;model_year:number|null;color:string|null;status:string;notes:string;authorized_driver_names?:string;current_driver_name?:string};
const emptyVehicle={internalCode:"",plateNumber:"",make:"",model:"",modelYear:"",color:"",status:"active",notes:""};
export function VehicleManager(){const[vehicles,setVehicles]=useState<Vehicle[]>([]),[form,setForm]=useState(emptyVehicle),[editing,setEditing]=useState<number|null>(null),[q,setQ]=useState(""),[message,setMessage]=useState("");const load=useCallback(async()=>setVehicles((await api<{vehicles:Vehicle[]}>(`/api/operational/vehicles?q=${encodeURIComponent(q)}`)).vehicles),[q]);useEffect(()=>{let active=true;void api<{vehicles:Vehicle[]}>(`/api/operational/vehicles?q=${encodeURIComponent(q)}`).then(x=>{if(active)setVehicles(x.vehicles)},e=>{if(active)setMessage(e.message)});return()=>{active=false}},[q]);async function save(){try{await api(editing?`/api/operational/vehicles/${editing}`:"/api/operational/vehicles",{method:editing?"PATCH":"POST",body:JSON.stringify(form)});setForm(emptyVehicle);setEditing(null);setMessage("تم حفظ السيارة.");await load()}catch(e){setMessage(e instanceof Error?e.message:"تعذر الحفظ")}}return <div className="op-manager"><section className="op-panel"><h2>{editing?"تعديل السيارة":"إضافة سيارة"}</h2><div className="op-form-grid">{[["internalCode","الكود الداخلي"],["plateNumber","رقم اللوحة"],["make","الماركة"],["model","الموديل"],["modelYear","سنة الصنع"],["color","اللون"]].map(([k,l])=><label key={k}>{l}<input value={form[k as keyof typeof form]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>الحالة<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">نشطة</option><option value="maintenance">صيانة</option><option value="inactive">غير نشطة</option><option value="retired">مؤرشفة</option></select></label><label>ملاحظات<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><button className="op-primary" onClick={()=>void save()}>حفظ</button>{message&&<p className="op-message">{message}</p>}</section><section className="op-panel"><input placeholder="بحث بالكود أو اللوحة" value={q} onChange={e=>setQ(e.target.value)}/><div className="op-table-wrap"><table><thead><tr><th>الكود</th><th>اللوحة</th><th>السيارة</th><th>الحالة</th><th>المصرح لهم</th><th>الحيازة الحالية</th><th></th></tr></thead><tbody>{vehicles.map(v=><tr key={v.id}><td>{v.internal_code}</td><td>{v.plate_number}</td><td>{v.make} {v.model}</td><td>{v.status}</td><td>{v.authorized_driver_names??"لا يوجد"}</td><td>{v.current_driver_name??"لا أحد"}</td><td><button onClick={()=>{setEditing(v.id);setForm({internalCode:v.internal_code,plateNumber:v.plate_number,make:v.make,model:v.model,modelYear:v.model_year?.toString()??"",color:v.color??"",status:v.status,notes:v.notes})}}>تعديل</button></td></tr>)}</tbody></table></div></section></div>}

export function SettingsManager({initial}:{initial:Record<string,string>}){const[form,setForm]=useState(initial),[message,setMessage]=useState("");async function save(){try{await api("/api/operational/settings",{method:"PATCH",body:JSON.stringify(form)});setMessage("تم حفظ الإعدادات.")}catch(e){setMessage(e instanceof Error?e.message:"تعذر الحفظ")}}return <section className="op-panel"><h2>الإعدادات العامة</h2><div className="op-form-grid"><label>اسم الشركة<input value={form.company_name??""} onChange={e=>setForm({...form,company_name:e.target.value})}/></label><label>اللغة<select value={form.default_language??"ar"} onChange={e=>setForm({...form,default_language:e.target.value})}><option value="ar">العربية</option><option value="en">English</option></select></label><label>المنطقة الزمنية<input value={form.timezone??""} onChange={e=>setForm({...form,timezone:e.target.value})}/></label><label>رابط نموذج الرحلات<input type="url" value={form.trips_form_url??""} onChange={e=>setForm({...form,trips_form_url:e.target.value})}/></label><label>إظهار زر الرحلات<select value={form.show_trips_button??"false"} onChange={e=>setForm({...form,show_trips_button:e.target.value})}><option value="false">لا</option><option value="true">نعم</option></select></label></div><button className="op-primary" onClick={()=>void save()}>حفظ الإعدادات</button>{message&&<p className="op-message">{message}</p>}</section>}
