"use client";
import { useCallback, useEffect, useState } from "react";

async function api<T>(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{"Content-Type":"application/json",...init?.headers}});const data=await response.json() as T&{error?:string};if(!response.ok)throw new Error(data.error??"تعذر إتمام العملية");return data;}
type Vehicle={id:number;internal_code:string;plate_number:string;make:string;model:string;model_year:number|null;color:string|null;vin:string|null;engine_number:string|null;fuel_type:string|null;current_odometer:number|null;vehicle_license_number:string|null;vehicle_type:string|null;registration_expires_at:string|null;insurance_expires_at:string|null;insurance_company:string|null;location:string|null;status:string;notes:string;authorized_driver_names?:string;current_driver_name?:string};
const empty={internalCode:"",plateNumber:"",make:"",model:"",modelYear:"",color:"",vin:"",engineNumber:"",fuelType:"",currentOdometer:"",vehicleLicenseNumber:"",vehicleType:"",registrationExpiresAt:"",insuranceExpiresAt:"",insuranceCompany:"",location:"",status:"active",notes:""};

export function VehicleManager(){
  const[vehicles,setVehicles]=useState<Vehicle[]>([]),[form,setForm]=useState(empty),[editing,setEditing]=useState<number|null>(null),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[locationFilter,setLocationFilter]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const p=new URLSearchParams({q:query,status,location:locationFilter});setVehicles((await api<{vehicles:Vehicle[]}>(`/api/operational/vehicles?${p}`)).vehicles)},[query,status,locationFilter]);
  useEffect(()=>{let active=true;const p=new URLSearchParams({q:query,status,location:locationFilter});void api<{vehicles:Vehicle[]}>(`/api/operational/vehicles?${p}`).then(result=>{if(active)setVehicles(result.vehicles)},error=>{if(active)setMessage(error instanceof Error?error.message:"تعذر التحميل")});return()=>{active=false}},[query,status,locationFilter]);
  async function save(){setBusy(true);setMessage("");try{await api(editing?`/api/operational/vehicles/${editing}`:"/api/operational/vehicles",{method:editing?"PATCH":"POST",body:JSON.stringify(form)});setForm(empty);setEditing(null);setMessage("تم حفظ السيارة من Move X.");await load()}catch(error){setMessage(error instanceof Error?error.message:"تعذر الحفظ")}finally{setBusy(false)}}
  function edit(vehicle:Vehicle){setEditing(vehicle.id);setForm({internalCode:vehicle.internal_code,plateNumber:vehicle.plate_number,make:vehicle.make,model:vehicle.model,modelYear:vehicle.model_year?.toString()??"",color:vehicle.color??"",vin:vehicle.vin??"",engineNumber:vehicle.engine_number??"",fuelType:vehicle.fuel_type??"",currentOdometer:vehicle.current_odometer?.toString()??"",vehicleLicenseNumber:vehicle.vehicle_license_number??"",vehicleType:vehicle.vehicle_type??"",registrationExpiresAt:vehicle.registration_expires_at??"",insuranceExpiresAt:vehicle.insurance_expires_at??"",insuranceCompany:vehicle.insurance_company??"",location:vehicle.location??"",status:vehicle.status,notes:vehicle.notes})}
  const field=(key:keyof typeof empty,label:string,type="text")=><label>{label}<input type={type} value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})}/></label>;
  return <div className="op-manager"><section className="op-panel"><h2>{editing?"تعديل السيارة":"إضافة سيارة"}</h2><div className="op-form-grid">{field("internalCode","الكود الداخلي")}{field("plateNumber","رقم اللوحة")}{field("make","الماركة")}{field("model","الموديل")}{field("modelYear","سنة الصنع","number")}{field("color","اللون")}{field("vin","رقم الهيكل VIN")}{field("engineNumber","رقم المحرك")}{field("fuelType","نوع الوقود")}{field("currentOdometer","العداد الحالي","number")}{field("vehicleLicenseNumber","رقم رخصة السيارة")}{field("vehicleType","نوع السيارة")}{field("registrationExpiresAt","انتهاء الترخيص","date")}{field("insuranceCompany","شركة التأمين")}{field("insuranceExpiresAt","انتهاء التأمين","date")}{field("location","الموقع")}<label>الحالة<select value={form.status} onChange={event=>setForm({...form,status:event.target.value})}><option value="active">نشطة</option><option value="maintenance">صيانة</option><option value="inactive">غير نشطة</option><option value="retired">مؤرشفة</option></select></label>{field("notes","ملاحظات")}</div><button className="op-primary" disabled={busy} onClick={()=>void save()}>حفظ السيارة</button>{editing&&<button className="op-secondary" disabled={busy} onClick={()=>{setEditing(null);setForm(empty)}}>إلغاء</button>}{message&&<p className="op-message" role="status">{message}</p>}</section><section className="op-panel"><div className="op-toolbar"><input placeholder="بحث بالكود أو اللوحة أو VIN" value={query} onChange={event=>setQuery(event.target.value)}/><input placeholder="تصفية بالموقع" value={locationFilter} onChange={event=>setLocationFilter(event.target.value)}/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">كل الحالات</option><option value="active">نشطة</option><option value="maintenance">صيانة</option><option value="inactive">غير نشطة</option><option value="retired">مؤرشفة</option></select></div><div className="op-table-wrap"><table><thead><tr><th>الكود</th><th>اللوحة</th><th>السيارة</th><th>VIN</th><th>الموقع</th><th>الحالة</th><th>المصرح لهم</th><th>الحيازة الحالية</th><th></th></tr></thead><tbody>{vehicles.map(vehicle=><tr key={vehicle.id}><td>{vehicle.internal_code}</td><td>{vehicle.plate_number}</td><td>{vehicle.make} {vehicle.model}</td><td>{vehicle.vin??"—"}</td><td>{vehicle.location??"—"}</td><td>{vehicle.status}</td><td>{vehicle.authorized_driver_names??"لا يوجد"}</td><td>{vehicle.current_driver_name??"لا أحد"}</td><td><button disabled={busy} onClick={()=>edit(vehicle)}>تعديل</button></td></tr>)}</tbody></table></div></section></div>;
}
