"use client";

import { useCallback, useEffect, useState } from "react";

async function api<T>(url:string,init?:RequestInit){
  const headers=init?.body instanceof FormData?init.headers:{"Content-Type":"application/json",...init?.headers};
  const response=await fetch(url,{...init,headers});const data=await response.json() as T&{error?:string};
  if(!response.ok)throw new Error(data.error??"تعذر إتمام العملية");return data;
}

type Vehicle={
  id:number;internal_code:string;plate_number:string;make:string;model:string;model_year:number|null;color:string|null;vin:string|null;
  engine_number:string|null;fuel_type:string|null;current_odometer:number|null;vehicle_license_number:string|null;vehicle_type:string|null;
  owner_name:string|null;traffic_department:string|null;traffic_unit:string|null;license_issue_date:string|null;registration_expires_at:string|null;
  tax_expires_at:string|null;technical_inspection_due:string|null;insurance_policy_number:string|null;insurance_expires_at:string|null;
  insurance_company:string|null;engine_capacity_cc:number|null;cylinder_count:number|null;legal_restrictions:string|null;location:string|null;
  status:string;notes:string;license_document_count?:number;authorized_driver_names?:string;current_driver_name?:string;
};
type VehicleDocument={id:number;document_type:string;original_filename:string;mime_type:string;file_size:number;verification_status:string;rejection_reason:string|null;archived_at:string|null};

const empty={internalCode:"",plateNumber:"",make:"",model:"",modelYear:"",color:"",vin:"",engineNumber:"",fuelType:"",currentOdometer:"",vehicleLicenseNumber:"",vehicleType:"",ownerName:"",trafficDepartment:"",trafficUnit:"",licenseIssueDate:"",registrationExpiresAt:"",taxExpiresAt:"",technicalInspectionDue:"",insurancePolicyNumber:"",insuranceExpiresAt:"",insuranceCompany:"",engineCapacityCc:"",cylinderCount:"",legalRestrictions:"",location:"",status:"active",notes:""};
const documentTypes={vehicle_license_front:"وجه رخصة التسيير",vehicle_license_back:"ظهر رخصة التسيير"};

export function VehicleManager(){
  const[vehicles,setVehicles]=useState<Vehicle[]>([]),[form,setForm]=useState(empty),[editing,setEditing]=useState<number|null>(null),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[locationFilter,setLocationFilter]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const[documents,setDocuments]=useState<VehicleDocument[]>([]),[storageConfigured,setStorageConfigured]=useState(false),[documentType,setDocumentType]=useState<keyof typeof documentTypes>("vehicle_license_front"),[file,setFile]=useState<File|null>(null);
  const load=useCallback(async()=>{const p=new URLSearchParams({q:query,status,location:locationFilter});setVehicles((await api<{vehicles:Vehicle[]}>(`/api/operational/vehicles?${p}`)).vehicles)},[query,status,locationFilter]);
  const loadDocuments=useCallback(async(vehicleId:number)=>{const result=await api<{documents:VehicleDocument[];storageConfigured:boolean}>(`/api/operational/vehicles/${vehicleId}/documents`);setDocuments(result.documents);setStorageConfigured(result.storageConfigured)},[]);
  useEffect(()=>{let active=true;const p=new URLSearchParams({q:query,status,location:locationFilter});void api<{vehicles:Vehicle[]}>(`/api/operational/vehicles?${p}`).then(result=>{if(active)setVehicles(result.vehicles)},error=>{if(active)setMessage(error instanceof Error?error.message:"تعذر التحميل")});return()=>{active=false}},[query,status,locationFilter]);

  async function save(){setBusy(true);setMessage("");try{await api(editing?`/api/operational/vehicles/${editing}`:"/api/operational/vehicles",{method:editing?"PATCH":"POST",body:JSON.stringify(form)});setForm(empty);setEditing(null);setDocuments([]);setMessage("تم حفظ بيانات السيارة ورخصة التسيير.");await load()}catch(error){setMessage(error instanceof Error?error.message:"تعذر الحفظ")}finally{setBusy(false)}}
  function edit(vehicle:Vehicle){setEditing(vehicle.id);setForm({internalCode:vehicle.internal_code,plateNumber:vehicle.plate_number,make:vehicle.make,model:vehicle.model,modelYear:vehicle.model_year?.toString()??"",color:vehicle.color??"",vin:vehicle.vin??"",engineNumber:vehicle.engine_number??"",fuelType:vehicle.fuel_type??"",currentOdometer:vehicle.current_odometer?.toString()??"",vehicleLicenseNumber:vehicle.vehicle_license_number??"",vehicleType:vehicle.vehicle_type??"",ownerName:vehicle.owner_name??"",trafficDepartment:vehicle.traffic_department??"",trafficUnit:vehicle.traffic_unit??"",licenseIssueDate:vehicle.license_issue_date??"",registrationExpiresAt:vehicle.registration_expires_at??"",taxExpiresAt:vehicle.tax_expires_at??"",technicalInspectionDue:vehicle.technical_inspection_due??"",insurancePolicyNumber:vehicle.insurance_policy_number??"",insuranceExpiresAt:vehicle.insurance_expires_at??"",insuranceCompany:vehicle.insurance_company??"",engineCapacityCc:vehicle.engine_capacity_cc?.toString()??"",cylinderCount:vehicle.cylinder_count?.toString()??"",legalRestrictions:vehicle.legal_restrictions??"",location:vehicle.location??"",status:vehicle.status,notes:vehicle.notes});setFile(null);void loadDocuments(vehicle.id)}
  function cancel(){setEditing(null);setForm(empty);setDocuments([]);setFile(null);setStorageConfigured(false)}
  async function upload(){if(!editing||!file)return;setBusy(true);setMessage("");try{const body=new FormData();body.set("file",file);body.set("documentType",documentType);await api(`/api/operational/vehicles/${editing}/documents`,{method:"POST",body});setFile(null);setMessage("تم رفع صورة الرخصة إلى مخزن المستندات الخاص.");await Promise.all([loadDocuments(editing),load()])}catch(error){setMessage(error instanceof Error?error.message:"تعذر رفع صورة الرخصة")}finally{setBusy(false)}}
  async function archive(documentId:number){if(!editing)return;setBusy(true);try{await api(`/api/operational/vehicle-documents/${documentId}`,{method:"DELETE"});setMessage("تمت أرشفة صورة الرخصة مع الاحتفاظ بسجل العملية.");await Promise.all([loadDocuments(editing),load()])}catch(error){setMessage(error instanceof Error?error.message:"تعذر الأرشفة")}finally{setBusy(false)}}
  async function review(documentId:number,status:'verified'|'rejected'){const rejectionReason=status==='rejected'?window.prompt("سبب الرفض")?.trim():"";if(status==='rejected'&&!rejectionReason)return;setBusy(true);try{await api(`/api/operational/vehicle-documents/${documentId}`,{method:"PATCH",body:JSON.stringify({status,rejectionReason})});setMessage(status==='verified'?"تم اعتماد صورة الرخصة.":"تم رفض الصورة وتسجيل السبب.");if(editing)await loadDocuments(editing)}catch(error){setMessage(error instanceof Error?error.message:"تعذر مراجعة الصورة")}finally{setBusy(false)}}
  const field=(key:keyof typeof empty,label:string,type="text")=><label>{label}<input type={type} value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})}/></label>;

  return <div className="op-manager">
    <section className="op-panel"><h2>{editing?"تعديل ملف السيارة":"إضافة سيارة"}</h2>
      <h3>البيانات الأساسية</h3><div className="op-form-grid">{field("internalCode","الكود الداخلي")}{field("plateNumber","رقم اللوحة")}{field("ownerName","اسم المالك")}{field("make","الماركة")}{field("model","الموديل")}{field("modelYear","سنة الصنع","number")}{field("color","اللون")}{field("vehicleType","نوع الترخيص / السيارة")}{field("vin","رقم الشاسيه VIN")}{field("engineNumber","رقم الموتور")}{field("engineCapacityCc","السعة اللترية (سم³)","number")}{field("cylinderCount","عدد الأسطوانات","number")}{field("fuelType","نوع الوقود")}{field("currentOdometer","العداد الحالي","number")}{field("location","الموقع")}</div>
      <h3>بيانات رخصة التسيير</h3><div className="op-form-grid">{field("vehicleLicenseNumber","رقم رخصة السيارة")}{field("trafficDepartment","إدارة المرور")}{field("trafficUnit","وحدة المرور")}{field("licenseIssueDate","تاريخ إصدار الرخصة","date")}{field("registrationExpiresAt","تاريخ انتهاء الترخيص","date")}{field("taxExpiresAt","تاريخ انتهاء الضريبة","date")}{field("technicalInspectionDue","الفحص الفني سنة أو تاريخ")}{field("insuranceCompany","شركة / جهة التأمين")}{field("insurancePolicyNumber","رقم وثيقة التأمين")}{field("insuranceExpiresAt","تاريخ انتهاء التأمين","date")}{field("legalRestrictions","الحظر أو القيود القانونية")}</div>
      <div className="op-form-grid"><label>حالة السيارة<select value={form.status} onChange={event=>setForm({...form,status:event.target.value})}><option value="active">نشطة</option><option value="maintenance">صيانة</option><option value="inactive">غير نشطة</option><option value="retired">مؤرشفة</option></select></label>{field("notes","ملاحظات")}</div>
      <button className="op-primary" disabled={busy} onClick={()=>void save()}>حفظ السيارة</button>{editing&&<button className="op-secondary" disabled={busy} onClick={cancel}>إلغاء</button>}{message&&<p className="op-message" role="status">{message}</p>}
    </section>

    {editing&&<section className="op-panel"><h2>صور رخصة التسيير</h2><p className="op-muted">تُحفظ الصورة في مخزن خاص، ولا تحفظ داخل D1 أو في GitHub، ولا تُعرض برابط عام.</p>
      {storageConfigured?<div className="document-upload"><label>جانب الرخصة<select value={documentType} onChange={event=>setDocumentType(event.target.value as keyof typeof documentTypes)}>{Object.entries(documentTypes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>صورة JPG أو PNG أو WEBP أو ملف PDF<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={event=>setFile(event.target.files?.[0]??null)}/></label><button className="op-primary" disabled={busy||!file} onClick={()=>void upload()}>رفع صورة الرخصة</button></div>:<div className="storage-blocker" role="status"><strong>رفع صورة الرخصة غير مفعّل على هذه البيئة</strong><p>يلزم إعداد Service Account ومجلد Google Drive الخاصين بالمستندات في Cloudflare Secrets. لن يظهر زر رفع غير عامل.</p></div>}
      <div className="op-table-wrap"><table><thead><tr><th>الجانب</th><th>الملف</th><th>الحجم</th><th>التحقق</th><th>إجراءات</th></tr></thead><tbody>{documents.filter(document=>!document.archived_at).map(document=><tr key={document.id}><td>{documentTypes[document.document_type as keyof typeof documentTypes]??document.document_type}</td><td>{document.original_filename}</td><td>{Math.ceil(document.file_size/1024)} KB</td><td>{document.verification_status}</td><td><a href={`/api/operational/vehicle-documents/${document.id}`} target="_blank" rel="noreferrer">عرض آمن</a> <button disabled={busy} onClick={()=>void review(document.id,'verified')}>اعتماد</button> <button disabled={busy} onClick={()=>void review(document.id,'rejected')}>رفض</button> <button disabled={busy} onClick={()=>void archive(document.id)}>أرشفة</button></td></tr>)}</tbody></table></div>
    </section>}

    <section className="op-panel"><div className="op-toolbar"><input placeholder="بحث بالكود أو اللوحة أو VIN" value={query} onChange={event=>setQuery(event.target.value)}/><input placeholder="تصفية بالموقع" value={locationFilter} onChange={event=>setLocationFilter(event.target.value)}/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">كل الحالات</option><option value="active">نشطة</option><option value="maintenance">صيانة</option><option value="inactive">غير نشطة</option><option value="retired">مؤرشفة</option></select></div><div className="op-table-wrap"><table><thead><tr><th>الكود</th><th>اللوحة</th><th>السيارة</th><th>المالك</th><th>انتهاء الترخيص</th><th>صور الرخصة</th><th>الموقع</th><th>الحالة</th><th>المصرح لهم</th><th>الحيازة الحالية</th><th></th></tr></thead><tbody>{vehicles.map(vehicle=><tr key={vehicle.id}><td>{vehicle.internal_code}</td><td>{vehicle.plate_number}</td><td>{vehicle.make} {vehicle.model}</td><td>{vehicle.owner_name??"—"}</td><td>{vehicle.registration_expires_at??"—"}</td><td>{Number(vehicle.license_document_count)||0}</td><td>{vehicle.location??"—"}</td><td>{vehicle.status}</td><td>{vehicle.authorized_driver_names??"لا يوجد"}</td><td>{vehicle.current_driver_name??"لا أحد"}</td><td><button disabled={busy} onClick={()=>edit(vehicle)}>فتح الملف</button></td></tr>)}</tbody></table></div></section>
  </div>;
}
