"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

async function api<T>(url:string,init?:RequestInit):Promise<T>{
  const response=await fetch(url,{...init,headers:{"Content-Type":"application/json",...init?.headers}});
  const data=await response.json() as T&{error?:string};
  if(!response.ok)throw new Error(data.error??"تعذر إتمام العملية");
  return data;
}

type Driver={id:number;loginCode:string;displayName:string};
type Vehicle={id:number;internal_code:string;plate_number:string;status:string;current_driver_name?:string;current_driver_user_id?:number};
type Authorization={id:number;driver_user_id:number;vehicle_id:number;driver_name:string;driver_code:string;internal_code:string;plate_number:string;shift_type:string;valid_from:string;valid_to:string|null;assignment_type:string;status:string;effective_status:string};
type Handover={id:number;vehicle_id:number;internal_code:string;plate_number:string;from_driver_name:string|null;to_driver_name:string;handed_over_at:string;received_at:string;odometer:number|null;fuel_level:number|null;vehicle_condition:string};
type Choice={selected:boolean;shiftType:string;assignmentType:string};

const shiftLabels:Record<string,string>={morning:"صباحية",evening:"مسائية",night:"ليلية",flexible:"مرنة"};
const assignmentLabels:Record<string,string>={primary:"أساسي",secondary:"ثانوي",backup:"بديل"};

export function VehicleOperationsManager(){
  const[drivers,setDrivers]=useState<Driver[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[assignments,setAssignments]=useState<Authorization[]>([]),[handovers,setHandovers]=useState<Handover[]>([]);
  const[vehicleId,setVehicleId]=useState(""),[choices,setChoices]=useState<Record<number,Choice>>({}),[validFrom,setValidFrom]=useState(""),[validTo,setValidTo]=useState("");
  const[handoverVehicleId,setHandoverVehicleId]=useState(""),[toDriverId,setToDriverId]=useState(""),[odometer,setOdometer]=useState(""),[fuelLevel,setFuelLevel]=useState(""),[vehicleCondition,setVehicleCondition]=useState("good"),[fuelNote,setFuelNote]=useState(""),[faultNotes,setFaultNotes]=useState(""),[generalNotes,setGeneralNotes]=useState("");
  const[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const result=await api<{assignments:Authorization[];drivers:Driver[];vehicles:Vehicle[]}>("/api/operational/assignments");const history=await api<{handovers:Handover[]}>("/api/operational/handovers");setDrivers(result.drivers);setVehicles(result.vehicles);setAssignments(result.assignments);setHandovers(history.handovers)},[]);
  useEffect(()=>{let active=true;void Promise.all([api<{assignments:Authorization[];drivers:Driver[];vehicles:Vehicle[]}>("/api/operational/assignments"),api<{handovers:Handover[]}>("/api/operational/handovers")]).then(([result,history])=>{if(active){setDrivers(result.drivers);setVehicles(result.vehicles);setAssignments(result.assignments);setHandovers(history.handovers)}},error=>{if(active)setMessage(error instanceof Error?error.message:"تعذر التحميل")});return()=>{active=false}},[]);
  const selected=Object.entries(choices).filter(([,value])=>value.selected);
  const activeForHandover=useMemo(()=>assignments.filter(item=>item.effective_status==="active"&&String(item.vehicle_id)===handoverVehicleId),[assignments,handoverVehicleId]);
  async function authorize(){if(!vehicleId||!selected.length)return;setBusy(true);setMessage("");try{await api("/api/operational/assignments",{method:"POST",body:JSON.stringify({vehicleId:Number(vehicleId),authorizations:selected.map(([id,value])=>({driverUserId:Number(id),shiftType:value.shiftType,assignmentType:value.assignmentType,validFrom:validFrom||undefined,validTo:validTo||undefined}))})});setMessage("تم حفظ السائقين المصرح لهم دون تغيير الحيازة الحالية.");setChoices({});setValidFrom("");setValidTo("");await load()}catch(error){setMessage(error instanceof Error?error.message:"تعذر حفظ التصاريح")}finally{setBusy(false)}}
  async function endAuthorization(id:number){setBusy(true);setMessage("");try{await api(`/api/operational/assignments/${id}`,{method:"DELETE"});setMessage("تم إنهاء تصريح القيادة مع الاحتفاظ بسجله.");await load()}catch(error){setMessage(error instanceof Error?error.message:"تعذر إنهاء التصريح")}finally{setBusy(false)}}
  async function handover(){if(!handoverVehicleId||!toDriverId)return;setBusy(true);setMessage("");try{await api("/api/operational/handovers",{method:"POST",body:JSON.stringify({vehicleId:Number(handoverVehicleId),toDriverUserId:Number(toDriverId),odometer:odometer||null,fuelLevel:fuelLevel||null,vehicleCondition,fuelNote,faultNotes,generalNotes})});setMessage("تم التسليم وتدوير الحيازة مع حفظ السجل الكامل.");setToDriverId("");setOdometer("");setFuelLevel("");setFuelNote("");setFaultNotes("");setGeneralNotes("");await load()}catch(error){setMessage(error instanceof Error?error.message:"تعذر إتمام التسليم")}finally{setBusy(false)}}
  return <div className="op-manager">
    <section className="op-panel"><h2>السائقون المصرح لهم</h2><p>اختر سيارة ثم سائقًا أو أكثر وحدد وردية كل سائق. هذا لا ينقل حيازة السيارة.</p><div className="op-form-grid"><label>السيارة<select value={vehicleId} onChange={event=>setVehicleId(event.target.value)}><option value="">اختر</option>{vehicles.filter(vehicle=>vehicle.status==="active").map(vehicle=><option key={vehicle.id} value={vehicle.id}>{vehicle.internal_code} — {vehicle.plate_number}</option>)}</select></label><label>بداية الصلاحية<input type="datetime-local" value={validFrom} onChange={event=>setValidFrom(event.target.value)}/></label><label>نهاية الصلاحية (اختياري)<input type="datetime-local" value={validTo} onChange={event=>setValidTo(event.target.value)}/></label></div><div className="op-driver-picker">{drivers.map(driver=>{const choice=choices[driver.id]??{selected:false,shiftType:"flexible",assignmentType:"secondary"};return <div key={driver.id}><label><input type="checkbox" checked={choice.selected} onChange={event=>setChoices({...choices,[driver.id]:{...choice,selected:event.target.checked}})}/><span>{driver.displayName}<small>{driver.loginCode}</small></span></label><select aria-label={`وردية ${driver.displayName}`} disabled={!choice.selected} value={choice.shiftType} onChange={event=>setChoices({...choices,[driver.id]:{...choice,shiftType:event.target.value}})}><option value="morning">صباحية</option><option value="evening">مسائية</option><option value="night">ليلية</option><option value="flexible">مرنة</option></select><select aria-label={`نوع تخصيص ${driver.displayName}`} disabled={!choice.selected} value={choice.assignmentType} onChange={event=>setChoices({...choices,[driver.id]:{...choice,assignmentType:event.target.value}})}><option value="primary">أساسي</option><option value="secondary">ثانوي</option><option value="backup">بديل</option></select></div>})}</div><button className="op-primary" disabled={busy||!vehicleId||!selected.length} onClick={()=>void authorize()}>حفظ التصاريح</button></section>
    <section className="op-panel"><h2>تسليم السيارة</h2><div className="op-form-grid"><label>السيارة<select value={handoverVehicleId} onChange={event=>{setHandoverVehicleId(event.target.value);setToDriverId("")}}><option value="">اختر</option>{vehicles.filter(vehicle=>vehicle.status==="active").map(vehicle=><option key={vehicle.id} value={vehicle.id}>{vehicle.internal_code} — الحيازة: {vehicle.current_driver_name??"لا أحد"}</option>)}</select></label><label>السائق المستلم<select value={toDriverId} onChange={event=>setToDriverId(event.target.value)}><option value="">اختر سائقًا مصرحًا</option>{activeForHandover.map(item=><option key={item.id} value={item.driver_user_id}>{item.driver_name} — {shiftLabels[item.shift_type]??item.shift_type}</option>)}</select></label><label>عداد الكيلومترات<input type="number" min="0" value={odometer} onChange={event=>setOdometer(event.target.value)}/></label><label>مستوى الوقود %<input type="number" min="0" max="100" value={fuelLevel} onChange={event=>setFuelLevel(event.target.value)}/></label><label>حالة السيارة<select value={vehicleCondition} onChange={event=>setVehicleCondition(event.target.value)}><option value="good">جيدة</option><option value="needs_attention">تحتاج متابعة</option><option value="damaged">بها تلف</option></select></label><label>ملاحظة الوقود<input value={fuelNote} onChange={event=>setFuelNote(event.target.value)}/></label><label>الأعطال<input value={faultNotes} onChange={event=>setFaultNotes(event.target.value)}/></label><label>ملاحظات عامة<input value={generalNotes} onChange={event=>setGeneralNotes(event.target.value)}/></label></div><button className="op-primary" disabled={busy||!handoverVehicleId||!toDriverId} onClick={()=>void handover()}>إتمام التسليم</button>{message&&<p className="op-message" role="status">{message}</p>}</section>
    <section className="op-panel"><h2>التصاريح الحالية والتاريخية</h2><div className="op-table-wrap"><table><thead><tr><th>السيارة</th><th>السائق</th><th>الوردية</th><th>النوع</th><th>الصلاحية</th><th>الحالة</th><th></th></tr></thead><tbody>{assignments.map(item=><tr key={item.id}><td>{item.internal_code} — {item.plate_number}</td><td>{item.driver_name}</td><td>{shiftLabels[item.shift_type]??item.shift_type}</td><td>{assignmentLabels[item.assignment_type]??item.assignment_type}</td><td>{item.valid_from}<br/>{item.valid_to??"مستمرة"}</td><td>{{active:"مصرح",scheduled:"مجدول",expired:"منتهي الصلاحية",ended:"منتهٍ"}[item.effective_status]??item.effective_status}</td><td>{item.status==="active"&&<button disabled={busy} onClick={()=>void endAuthorization(item.id)}>إنهاء التصريح</button>}</td></tr>)}</tbody></table></div></section>
    <section className="op-panel"><h2>سجل الاستلام والتسليم</h2><div className="op-table-wrap"><table><thead><tr><th>السيارة</th><th>من</th><th>إلى</th><th>وقت الاستلام</th><th>العداد</th><th>الوقود</th><th>الحالة</th></tr></thead><tbody>{handovers.map(item=><tr key={item.id}><td>{item.internal_code} — {item.plate_number}</td><td>{item.from_driver_name??"بداية التشغيل"}</td><td>{item.to_driver_name}</td><td>{item.received_at}</td><td>{item.odometer??"—"}</td><td>{item.fuel_level===null?"—":`${item.fuel_level}%`}</td><td>{item.vehicle_condition}</td></tr>)}</tbody></table></div></section>
  </div>;
}
